image: node:latest

frontend:
  cache:
    paths:
      - frontend/node_modules/
      - frontend/build/

  before_script:
    - cd frontend && npm install

  tests:
    script:
      - npm test
  build:
    script:
      - npm run build

backend:
  cache:
    paths:
      - backend/node_modules/

  before_script:
    - cd backend && npm install

  tests:
    script:
      - npm test