image: node:latest

stages:
  - lint
  - build
  - tests

Lint-Frontent:
  stage: lint
  before_script:
    - cd frontend && npm install
  script:
    - npm run lint

Build-Frontend:
  stage: build
  cache:
    paths:
      - frontend/node_modules/
      - frontend/build/
  before_script:
    - cd frontend && npm install
  script:
    - npm run build
  
Test-Frontend:
  stage: tests
  cache:
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend && npm install
  script:
    - npm run test


Lint-Backend:
  stage: lint
  before_script:
    - cd backend && npm install
  script:
    - npm run lint

Test-Backend:
  stage: tests
  cache:
    paths:
      - backend/node_modules/
  before_script:
    - cd backend && npm install
  script:
    - npm run test


    

