image: node:latest

cache:
  paths:
    - frontend/node_modules/
    - frontend/build/

before_script:
  - cd frontend && npm install

all_tests:
  script:
    - cd frontend
    - npm test
    - npm run build